# Generated by Django 3.2.16 on 2022-11-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0007_auto_20221122_1743"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="s3_live_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
