# Generated by Django 3.2.16 on 2022-11-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0009_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="filename",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="size",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="version",
            name="width",
            field=models.IntegerField(null=True),
        ),
    ]
