# Generated by Django 3.2.16 on 2022-11-26 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0011_auto_20221126_0055"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="photo_uuid",
        ),
        migrations.AddField(
            model_name="version",
            name="photo",
            field=models.ForeignKey(
                db_column="photo_uuid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="photos.photo",
            ),
            preserve_default=False,
        ),
    ]
