# Generated by Django 3.2.19 on 2023-07-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0013_auto_20221128_1828"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="library",
            field=models.TextField(blank=True, null=True),
        ),
    ]
