"""Initial migration with User, Photo, Album, and Version models

Revision ID: 49348f7a48f6
Revises:
Create Date: 2025-12-06 00:46:17.340839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49348f7a48f6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("date_joined", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "photos",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("masterFingerprint", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("keywords", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("labels", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("albums", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("persons", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("faces", postgresql.JSONB(), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=True),
        sa.Column("hidden", sa.Boolean(), nullable=True),
        sa.Column("isphoto", sa.Boolean(), nullable=True),
        sa.Column("ismovie", sa.Boolean(), nullable=True),
        sa.Column("burst", sa.Boolean(), nullable=True),
        sa.Column("live_photo", sa.Boolean(), nullable=True),
        sa.Column("portrait", sa.Boolean(), nullable=True),
        sa.Column("screenshot", sa.Boolean(), nullable=True),
        sa.Column("slow_mo", sa.Boolean(), nullable=True),
        sa.Column("time_lapse", sa.Boolean(), nullable=True),
        sa.Column("hdr", sa.Boolean(), nullable=True),
        sa.Column("selfie", sa.Boolean(), nullable=True),
        sa.Column("panorama", sa.Boolean(), nullable=True),
        sa.Column("intrash", sa.Boolean(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("uti", sa.Text(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("place", postgresql.JSONB(), nullable=True),
        sa.Column("exif", postgresql.JSONB(), nullable=True),
        sa.Column("score", postgresql.JSONB(), nullable=True),
        sa.Column("search_info", postgresql.JSONB(), nullable=True),
        sa.Column("fields", postgresql.JSONB(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("orientation", sa.Integer(), nullable=True),
        sa.Column("s3_key_path", sa.Text(), nullable=True),
        sa.Column("s3_thumbnail_path", sa.Text(), nullable=True),
        sa.Column("s3_edited_path", sa.Text(), nullable=True),
        sa.Column("s3_original_path", sa.Text(), nullable=True),
        sa.Column("s3_live_path", sa.Text(), nullable=True),
        sa.Column("library", sa.Text(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "album_photos",
        sa.Column("album_uuid", sa.String(), nullable=True),
        sa.Column("photo_uuid", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_uuid"],
            ["albums.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_uuid"],
            ["photos.uuid"],
        ),
    )
    op.create_table(
        "versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("photo_uuid", sa.String(), nullable=True),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("s3_path", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["photo_uuid"],
            ["photos.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_versions_id"), "versions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_versions_id"), table_name="versions")
    op.drop_table("versions")
    op.drop_table("album_photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("albums")
    # ### end Alembic commands ###
