"""Add Library model for multiple libraries per user

Revision ID: c71fdf3b7df8
Revises: a1b2c3d4e5f6
Create Date: 2025-12-06 06:42:20.531017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71fdf3b7df8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libraries_id'), 'libraries', ['id'], unique=False)
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_photos_library_id', 'libraries', ['library_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_photos_library_id', type_='foreignkey')
        batch_op.drop_column('library_id')
    
    op.drop_index(op.f('ix_libraries_id'), table_name='libraries')
    op.drop_table('libraries')
    # ### end Alembic commands ###
