/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    Login: typeof import("./components/Login.vue")["default"];
    PhotoGallery: typeof import("./components/PhotoGallery.vue")["default"];
    PhotoUpload: typeof import("./components/PhotoUpload.vue")["default"];
    Register: typeof import("./components/Register.vue")["default"];
  }
}
