/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Login: typeof import('./src/components/Login.vue')['default']
    PhotoGallery: typeof import('./src/components/PhotoGallery.vue')['default']
    PhotoUpload: typeof import('./src/components/PhotoUpload.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
  }
}
