# Generated by Django 3.1.8 on 2021-06-04 04:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('masterFingerprint', models.TextField(unique=True)),
                ('filename', models.TextField()),
                ('original_filename', models.TextField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('albums', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('folders', models.JSONField(null=True)),
                ('persons', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('faces', models.JSONField(null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('ismissing', models.BooleanField(null=True)),
                ('hasadjustments', models.BooleanField(null=True)),
                ('external_edit', models.BooleanField(null=True)),
                ('favorite', models.BooleanField(null=True)),
                ('hidden', models.BooleanField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('path_edited', models.TextField(blank=True, null=True)),
                ('shared', models.BooleanField(null=True)),
                ('isphoto', models.BooleanField(null=True)),
                ('ismovie', models.BooleanField(null=True)),
                ('uti', models.TextField(blank=True, null=True)),
                ('uti_original', models.TextField(blank=True, null=True)),
                ('burst', models.BooleanField(null=True)),
                ('live_photo', models.BooleanField(null=True)),
                ('path_live_photo', models.TextField(blank=True, null=True)),
                ('iscloudasset', models.BooleanField(null=True)),
                ('incloud', models.BooleanField(null=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('portrait', models.BooleanField(null=True)),
                ('screenshot', models.BooleanField(null=True)),
                ('slow_mo', models.BooleanField(null=True)),
                ('time_lapse', models.BooleanField(null=True)),
                ('hdr', models.BooleanField(null=True)),
                ('selfie', models.BooleanField(null=True)),
                ('panorama', models.BooleanField(null=True)),
                ('has_raw', models.BooleanField(null=True)),
                ('israw', models.BooleanField(null=True)),
                ('raw_original', models.BooleanField(null=True)),
                ('uti_raw', models.TextField(blank=True, null=True)),
                ('path_raw', models.TextField(blank=True, null=True)),
                ('place', models.JSONField(null=True)),
                ('exif', models.JSONField(null=True)),
                ('score', models.JSONField(null=True)),
                ('intrash', models.BooleanField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('orientation', models.IntegerField(null=True)),
                ('original_height', models.IntegerField(null=True)),
                ('original_width', models.IntegerField(null=True)),
                ('original_orientation', models.IntegerField(null=True)),
                ('original_filesize', models.IntegerField(null=True)),
                ('comments', models.JSONField(null=True)),
                ('likes', models.JSONField(null=True)),
                ('search_info', models.JSONField(null=True)),
                ('s3_key_path', models.TextField(blank=True, null=True)),
                ('s3_thumbnail_path', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
