# Generated by Django 3.1.8 on 2021-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210607_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='s3_edited_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
