# Generated by Django 3.1.8 on 2021-09-26 20:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photos", "0005_photo_owner"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="photo",
            index_together={("date", "owner")},
        ),
    ]
