# Generated by Django 3.2.16 on 2022-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20221126_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='hdr',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='ismovie',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='isphoto',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='panorama',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='screenshot',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='selfie',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='slow_mo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='time_lapse',
            field=models.BooleanField(null=True),
        ),
    ]
