# Generated by Django 3.2.25 on 2024-11-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_version_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='fields',
            field=models.JSONField(null=True),
        ),
    ]
