version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  # cookies: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: photosafe_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: photosafe_local_node
    container_name: node
    volumes:
      - ./frontend/src:/app/src:z
    environment:
      - REACT_APP_SERVER_ADDRESS=http://localhost:8000
    depends_on:
      - django
    ports:
      - "3000:3000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: photosafe_production_postgres
    container_name: postgres
    ports:
      - 5432
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  #  docs:
  #    image: photosafe_local_docs
  #    container_name: docs
  #    build:
  #      context: .
  #      dockerfile: ./compose/local/docs/Dockerfile
  #    env_file:
  #      - ./.envs/.local/.django
  #    volumes:
  #      - ./docs:/docs:z
  #      - ./config:/app/config:z
  #      - ./photosafe:/app/photosafe:z
  #    ports:
  #      - "7000:7000"
  #    command: /start-docs

  redis:
    image: redis:5.0
    container_name: redis

  # celeryworker:
  #   <<: *django
  #   image: photosafe_local_celeryworker
  #   container_name: celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celeryworker
  #   volumes:
  #     - cookies:/tmp:z

  # celerybeat:
  #   <<: *django
  #   image: photosafe_local_celerybeat
  #   container_name: celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: photosafe_local_flower
  #   container_name: flower
  #   ports:
  #     - "5555:5555"
  #   command: /start-flower
